### ISSUE TITLE
compile error viewpoint_estimation_service.srv is missing

### ISSUE THREAD

**Issue by zweistein** [durovsky/marker_pose_detection#1]
I try to use your pkg in `ROS Indigo` but when I compile I receive an error:
ese message generators: gencpp;geneus;genlisp;genpy
`CMake Error at /opt/ros/indigo/share/genmsg/cmake/genmsg-extras.cmake:148 (message):
  add_service_files() directory not found:
  /home/elod/catkin_ws/src/vision/marker_pose_detection-master/srv
Call Stack (most recent call first):
  vision/marker_pose_detection-master/CMakeLists.txt:26 (add_service_files)
-- Configuring incomplete, errors occurred!`

and this point to the line in your cmake file:
`add_service_files(FILES viewpoint_estimation_service.srv)`

So, I checked the source and I cant find any `viewpoint_estimation_service.srv`, which sould be the problem, could you please help me and commit this one too?

**Comment by durovsky** [comment]
Thanks for bug report, `add_service_files` is probably forgotten line from previous CMake version, according to the code, the result of processing is being published to topic, no services are included . Try new CMake and let me know if it works, I actually don't have setup with all dependencies installed to test it.

**Comment by zweistein** [comment]
I just took out the `add_service_files` and I could compile. I have some other issues, Rvec and Tvec are 0 all the time and I get a warning for camera calibration for my calib data and also for the example genius100 data set. Could this be a problem?

**Update** yes, calibration file load was the issue with detection.
